spring:
  application:
    name: bullet-agg
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
#        server-addr: 127.0.0.1:8848
        server-addr: 192.168.22.129:8848

server:
  port: 8087

spring.kafka.consumer.group-id: bullet-agg
spring.kafka.nodes: 192.168.22.129:9092
spring.kafka.consumer.auto-offset-reset: earliest

spring.redis.cluster.nodes: 82.157.68.174:7001,82.157.68.174:7002,82.157.68.174:7003

