spring:
  application:
    name: bullet-comet
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
#        server-addr: 127.0.0.1:8848
        server-addr: 39.105.34.3:8848

server:
  port: 8895